### ISSUE TITLE
Github stats are ignoring private repos by default

### ISSUE THREAD

**Issue by fx2000** [arturssmirnovs/github-profile-readme-generator#13]
Would be nice to have an extra checkbox in the Statistics section that would enable showing private repos in the graph.

**Comment by fx2000** [comment]
I took a crack at it and it turned out to be a pretty simple implementation, please check it out and let me know if you have any feedback.

https://github.com/arturssmirnovs/github-profile-readme-generator/pull/14

**Comment by arturssmirnovs** [comment]
Nice, didn't know that feature existed.. Thanks for contributing..
