### ISSUE TITLE
Have you considered internationalization?

### ISSUE THREAD

**Issue by fx2000** [arturssmirnovs/github-profile-readme-generator#22]
Adding just one extra language is an easy to way to reach a lot more people.

**Comment by fx2000** [comment]
I gave this a try based on [@andreasremdt's](https://github.com/andreasremdt/) [simple-translator](https://github.com/andreasremdt/simple-translator) library implementation. It works "ok" for english and spanish right now but there's a couple of hard-coded things that will need to be updated if you plan to add additional languages. More info about it in PR https://github.com/arturssmirnovs/github-profile-readme-generator/pull/25

![image](https://user-images.githubusercontent.com/11317662/96063537-5b36d680-0e5d-11eb-851b-36dc325c398c.png)

**Comment by arturssmirnovs** [comment]
Thanks mate, merged your PR's ... 
I restructured code  base abit to fit project coding pattern.. 

Thanks for contribution
