### ISSUE TITLE
Purchase custom domain for this project?

### ISSUE THREAD

**Issue by arturssmirnovs** [arturssmirnovs/github-profile-readme-generator#26]
What your thought's on purchasing custom domain for this project?

and placing it on something like: xxxxxxxxxxxxxx.com
not : https://arturssmirnovs.github.io/github-profile-readme-generator/

**Comment by max-programming** [comment]
@arturssmirnovs I think we should use bitly to shorten this link. What do you think

**Comment by arturssmirnovs** [comment]
Yes, sure, but still be could have bitly -> domain.com ...
And maybe make this project more then just generator.. we could implament this: https://raw.githubusercontent.com/zzetao/awesome-github-profile-data/master/data.json to make something like (https://zzetao.github.io/awesome-github-profile/) on seperate page, add resources  page.. 

Etc, make proper page that's all about github readme..

**Comment by max-programming** [comment]
So extending this project and adding more and more things. Nice idea! I will try to share this to some big devs. And let you know some ideas with issues. It'll be a good opportunity for me too as I am only 15 and still haven't collaborated with anyone on any project.
If you see my [Max Todos Repo](https://github.com/max-programming/max-todos/#-features-in-mind), here, I have some checkboxes in the README, Maybe we can add those so that we write down what features we want to add

**Comment by fx2000** [comment]
www.githubread.me is available and .me domains are like 3 euros a year, could be an interesting option.

https://domain.me/?output=nice&origin=content&query=githubread

**Comment by arturssmirnovs** [comment]
githubread.me Uh, this is nice..

Yeah, but overall question if this is necessary? 

Have proper website with features like:

Home page
Generator (current project)
Resources (List with articles about readme profile)
Showcases (List with cool github profiles)

**Comment by max-programming** [comment]
I think it is a good idea to purchase one. **BUT!** We should work on these things first, and then buy a domain

**Comment by fx2000** [comment]
> githubread.me Uh, this is nice..
> 
> Yeah, but overall question if this is necessary?
> 
> Have proper website with features like:
> 
> Home page
> Generator (current project)
> Resources (List with articles about readme profile)
> Showcases (List with cool github profiles)

I think a short domain is a good idea, but I would keep it VERY light, just the tool straight up as you load the URL. Maybe you can put a navbar on top with links to the repo or a donation page, but I would steer clear of clutter, this is the kind of tool people don't want to spend too much time on and simplicity is key.

**Comment by DenverCoder1** [comment]
If this is of any interest, GitHub has a URL shortener specifically for Github domains called git.io

You can claim a custom domain with cURL - https://gist.github.com/dikiaap/01f5e2ba3c738012aef0a8f524a6e207

**Comment by arturssmirnovs** [comment]
Thanks everyone for feedback, will see how it goes, maybe in future let's get a domain, but i guess at the moment let's stick to this one..
