### ISSUE TITLE
Add constributers in readme file

### ISSUE THREAD

**Issue by arturssmirnovs** [arturssmirnovs/github-profile-readme-generator#28]
Somebody could add:

https://github.com/arturssmirnovs
https://github.com/max-programming
https://github.com/fx2000

On readme.md as TOP Contributors

**Comment by fx2000** [comment]
Created PR https://github.com/arturssmirnovs/github-profile-readme-generator/pull/29

**Comment by max-programming** [comment]
Thanks for making me a top contributor ❤️
