### ISSUE TITLE
How about changing the cover image?

### ISSUE THREAD

**Issue by max-programming** [arturssmirnovs/github-profile-readme-generator#30]
I thought to create a new cover image for our generator. Thinking of changing the default one. What do you think?
![GitHub Profile README Generator](https://user-images.githubusercontent.com/51731966/96397647-89af0b80-11e7-11eb-8183-e227324d0a0a.png)

**Comment by arturssmirnovs** [comment]
Yup, agree.. looks nice :)

**Comment by max-programming** [comment]
Ok! I will change it on the site and in the README
