### ISSUE TITLE
How about deploying it on Netlify?

### ISSUE THREAD

**Issue by max-programming** [arturssmirnovs/github-profile-readme-generator#37]
If we deploy the site on Netlify, We would be able to track every PR's changes on a different deployed URL. Because of the tests ran by Netlify. So that we can see a demo and let them know if we are facing any issues. I don't know if a demo site is provided by GitHub pages

**Comment by arturssmirnovs** [comment]
mm.. I guess at the moment let's stick to GitHub pages..
When there is advanced PR I usually checkout that branch on my PC and run it from localhost..
After that merge in to master on localhost and push in to master..
Works good enough..

**Comment by max-programming** [comment]
Ok. np, that's also good move. I'll check if there's something we can do like Netlify provides
