### ISSUE TITLE
Hacktoberfest contributions 

### ISSUE THREAD

**Issue by fx2000** [arturssmirnovs/github-profile-readme-generator#39]
Can you guys please add hacktobefest-accepted tags to the PRs made during Hacktoberfest? Right now a bunch of them are showing as ineligible.

**Comment by max-programming** [comment]
Might be possible because the `hacktoberfest` topic has been removed from the repo. I think we should add those labels as well as the topic.
@arturssmirnovs Would you add that topic back? I will add those labels on the PRs

**Comment by arturssmirnovs** [comment]
@fx2000 Done, added both, hacktobefest-accepted labels + hacktoberfest hashtag back to repository..
Can you approve that this is solved?
