### ISSUE TITLE
Contribution graph option can be added too

### ISSUE THREAD

**Issue by Ashutosh00710** [arturssmirnovs/github-profile-readme-generator#42]
**Description**
I have created a readme project [github-readme-activity-graph](https://github.com/Ashutosh00710/github-readme-activity-graph) which will show your recent GitHub activity (contributions) with a attractive graph SVG.

Link to the repository: https://github.com/Ashutosh00710/github-readme-activity-graph

Additional context
Demo/Example:
[![Ashutosh's github activity graph](https://activity-graph.herokuapp.com/graph?username=arturssmirnovs&theme=rogue&area=true)](https://github.com/ashutosh00710/github-readme-activity-graph)

**Comment by max-programming** [comment]
Wow Ashutosh! This seems very interesting. Do you want to add it yourself or do you want us to add it?

**Comment by Ashutosh00710** [comment]
Thanks for your appreciation @max-programming. If it's not a problem, you can add it. 🙂

**Comment by max-programming** [comment]
Sure! I'll try to do it as I get time!

**Comment by max-programming** [comment]
Done at 5aeedd46d6e4541c05e1340017e3f7942cebc473. Thanks for letting us know about this feature
