### ISSUE TITLE
Can you integrate GitHub Profile Trophy to your service?

### ISSUE THREAD

**Issue by ryo-ma** [arturssmirnovs/github-profile-readme-generator#5]
I have developed GitHub Profile Trophy.

https://github.com/ryo-ma/github-profile-trophy

Can you integrate into the functionality in the same like as Github readme stats?

<img width="1317" alt="スクリーンショット 2020-08-30 22 03 37" src="https://user-images.githubusercontent.com/6661165/91737154-a8caed00-ebe9-11ea-83f8-18f2e3449094.png">

**Comment by arturssmirnovs** [comment]
To be honest I was thinking about it :)
Have seen your project before..

Will do mate, when done will let you know :)

**Comment by ryo-ma** [comment]
That's great! I am very honored.

**Comment by arturssmirnovs** [comment]
My pleasure! Thanks for your project as well.. 
Added your trophies and in readme link to your project. (You could like me back in your project as well, would appreciate.)

**Comment by ryo-ma** [comment]
Thanks! Great work!
