### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by MrCheesyBytes** [arturssmirnovs/github-profile-readme-generator#50]
An error occurred when choosing an icon.

![image](https://github.com/arturssmirnovs/github-profile-readme-generator/assets/135207728/34362579-d889-4040-bf8f-4f869e68c7e1)
Error code: **STATUS_BREAKPOINT**

**Comment by PREETCHAUHAN** [comment]
Use This Bro https://profile-readme-generator.com/
